import type { SectionDefinition } from "./definitions";

/**
 * The built-in section catalog. Adding a new built-in section means appending
 * an object here — no editor, preview, or LaTeX code changes required.
 *
 * `renderer` keys resolve in the preview/LaTeX renderer registries; entries
 * that don't match any key fall back to the generic renderer.
 */
export const builtinSectionDefinitions: SectionDefinition[] = [
  {
    id: "profile",
    title: "Personal Information",
    icon: "user",
    type: "single",
    renderer: "profile",
    defaultVisible: true,
    order: 0,
    fields: [
      { id: "fullName", label: "Full name", type: "text", required: true },
      { id: "preferredName", label: "Preferred name", type: "text" },
      { id: "email", label: "Email", type: "email" },
      { id: "phone", label: "Phone", type: "text" },
      { id: "address", label: "Address", type: "text" },
      { id: "city", label: "City", type: "text" },
      { id: "state", label: "State/Province", type: "text" },
      { id: "country", label: "Country", type: "text" },
      { id: "website", label: "Website", type: "url" },
      { id: "googleScholar", label: "Google Scholar", type: "url" },
      { id: "orcid", label: "ORCID", type: "url" },
      { id: "linkedin", label: "LinkedIn", type: "url" },
      { id: "github", label: "GitHub", type: "url" },
      { id: "otherUrls", label: "Other URLs", type: "textarea", helpText: "One per line" },
    ],
  },
  {
    id: "education",
    title: "Education",
    icon: "graduation-cap",
    type: "collection",
    renderer: "education",
    defaultVisible: true,
    order: 10,
    fields: [
      { id: "degree", label: "Degree", type: "text", required: true },
      { id: "fieldOfStudy", label: "Field of study", type: "text" },
      { id: "institution", label: "Institution", type: "text", required: true },
      { id: "department", label: "Department", type: "text" },
      { id: "location", label: "Location", type: "text" },
      { id: "startYear", label: "Start year", type: "year" },
      { id: "endYear", label: "End year", type: "year" },
      { id: "isPresent", label: "Present / Expected", type: "checkbox" },
      { id: "advisor", label: "Advisor", type: "text" },
      { id: "thesisTitle", label: "Thesis/dissertation title", type: "text" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "positions",
    title: "Academic Positions",
    icon: "briefcase",
    type: "collection",
    renderer: "position",
    defaultVisible: true,
    order: 20,
    fields: [
      { id: "position", label: "Position", type: "text", required: true },
      { id: "institution", label: "Institution", type: "text", required: true },
      { id: "department", label: "Department", type: "text" },
      { id: "location", label: "Location", type: "text" },
      { id: "startYear", label: "Start year", type: "year" },
      { id: "endYear", label: "End year", type: "year" },
      { id: "isPresent", label: "Current position", type: "checkbox" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "research",
    title: "Research Experience",
    icon: "flask-conical",
    type: "collection",
    renderer: "generic",
    defaultVisible: true,
    order: 30,
    fields: [
      { id: "role", label: "Position/role", type: "text" },
      { id: "project", label: "Project", type: "text" },
      { id: "institution", label: "Institution", type: "text" },
      { id: "advisor", label: "Advisor", type: "text" },
      { id: "startYear", label: "Start year", type: "year" },
      { id: "endYear", label: "End year", type: "year" },
      { id: "isPresent", label: "Ongoing", type: "checkbox" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "publications",
    title: "Publications",
    icon: "book-open",
    type: "collection",
    renderer: "publication",
    defaultVisible: true,
    order: 40,
    fields: [
      {
        id: "type",
        label: "Publication type",
        type: "select",
        options: [
          { value: "journal", label: "Journal Article" },
          { value: "conference", label: "Conference Paper" },
          { value: "workshop", label: "Workshop Paper" },
          { value: "book", label: "Book" },
          { value: "bookChapter", label: "Book Chapter" },
          { value: "preprint", label: "Preprint" },
          { value: "technicalReport", label: "Technical Report" },
          { value: "other", label: "Other" },
        ],
      },
      { id: "title", label: "Title", type: "text", required: true },
      { id: "authors", label: "Authors", type: "authors" },
      { id: "venue", label: "Venue/journal/conference", type: "text" },
      { id: "year", label: "Year", type: "year" },
      { id: "volume", label: "Volume", type: "text" },
      { id: "issue", label: "Issue", type: "text" },
      { id: "pages", label: "Pages", type: "text" },
      { id: "doi", label: "DOI", type: "text" },
      { id: "url", label: "URL", type: "url" },
      {
        id: "status",
        label: "Status",
        type: "select",
        options: [
          { value: "published", label: "Published" },
          { value: "accepted", label: "Accepted" },
          { value: "inPress", label: "In Press" },
          { value: "underReview", label: "Under Review" },
          { value: "preprint", label: "Preprint" },
        ],
      },
    ],
  },
  {
    id: "teaching",
    title: "Teaching Experience",
    icon: "presentation",
    type: "collection",
    renderer: "generic",
    defaultVisible: false,
    order: 50,
    fields: [
      { id: "course", label: "Course", type: "text", required: true },
      { id: "courseNumber", label: "Course number", type: "text" },
      { id: "institution", label: "Institution", type: "text" },
      {
        id: "role",
        label: "Role",
        type: "select",
        options: [
          { value: "instructor", label: "Instructor" },
          { value: "ta", label: "Teaching Assistant" },
          { value: "coInstructor", label: "Co-Instructor" },
          { value: "guestLecturer", label: "Guest Lecturer" },
          { value: "other", label: "Other" },
        ],
      },
      {
        id: "semester",
        label: "Semester",
        type: "select",
        options: [
          { value: "fall", label: "Fall" },
          { value: "spring", label: "Spring" },
          { value: "summer", label: "Summer" },
          { value: "winter", label: "Winter" },
        ],
      },
      { id: "year", label: "Year", type: "year" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "awards",
    title: "Awards and Honors",
    icon: "trophy",
    type: "collection",
    renderer: "generic",
    defaultVisible: true,
    order: 60,
    fields: [
      { id: "award", label: "Award", type: "text", required: true },
      { id: "organization", label: "Organization", type: "text" },
      { id: "year", label: "Year", type: "year" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "grants",
    title: "Grants and Fellowships",
    icon: "award",
    type: "collection",
    renderer: "generic",
    defaultVisible: false,
    order: 70,
    fields: [
      { id: "name", label: "Grant/fellowship name", type: "text", required: true },
      { id: "organization", label: "Organization", type: "text" },
      {
        id: "role",
        label: "Role",
        type: "select",
        options: [
          { value: "pi", label: "Principal Investigator" },
          { value: "coPi", label: "Co-Principal Investigator" },
          { value: "coI", label: "Co-Investigator" },
          { value: "postdocFellow", label: "Postdoctoral Fellow" },
          { value: "other", label: "Other" },
        ],
      },
      { id: "amount", label: "Amount", type: "text" },
      { id: "startYear", label: "Start year", type: "year" },
      { id: "endYear", label: "End year", type: "year" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "talks",
    title: "Talks and Presentations",
    icon: "mic",
    type: "collection",
    renderer: "generic",
    defaultVisible: true,
    order: 80,
    fields: [
      { id: "title", label: "Title", type: "text", required: true },
      { id: "event", label: "Event", type: "text" },
      { id: "organization", label: "Institution/Organization", type: "text" },
      { id: "location", label: "Location", type: "text" },
      { id: "date", label: "Date", type: "date" },
      {
        id: "type",
        label: "Type",
        type: "select",
        options: [
          { value: "invited", label: "Invited Talk" },
          { value: "conference", label: "Conference Presentation" },
          { value: "seminar", label: "Seminar" },
          { value: "poster", label: "Poster" },
          { value: "workshop", label: "Workshop" },
          { value: "guestLecture", label: "Guest Lecture" },
          { value: "other", label: "Other" },
        ],
      },
      { id: "url", label: "URL", type: "url" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "service",
    title: "Academic Service",
    icon: "handshake",
    type: "collection",
    renderer: "generic",
    defaultVisible: false,
    order: 90,
    fields: [
      { id: "organization", label: "Organization", type: "text", required: true },
      { id: "role", label: "Role", type: "text" },
      { id: "startYear", label: "Start year", type: "year" },
      { id: "endYear", label: "End year", type: "year" },
      { id: "isPresent", label: "Ongoing", type: "checkbox" },
      { id: "description", label: "Description", type: "textarea" },
    ],
  },
  {
    id: "skills",
    title: "Skills",
    icon: "wrench",
    type: "collection",
    renderer: "categoryList",
    defaultVisible: false,
    order: 100,
    fields: [
      { id: "category", label: "Category", type: "text", required: true },
      {
        id: "items",
        label: "Skills",
        type: "textarea",
        helpText: "Comma or newline separated",
      },
    ],
  },
  {
    id: "languages",
    title: "Languages",
    icon: "globe",
    type: "collection",
    renderer: "generic",
    defaultVisible: false,
    order: 110,
    fields: [
      { id: "language", label: "Language", type: "text", required: true },
      {
        id: "proficiency",
        label: "Proficiency",
        type: "select",
        options: [
          { value: "native", label: "Native" },
          { value: "fluent", label: "Fluent" },
          { value: "advanced", label: "Advanced" },
          { value: "intermediate", label: "Intermediate" },
          { value: "basic", label: "Basic" },
        ],
      },
    ],
  },
];
